#!/bin/bash

echo 'Checking coverage...'
pytest --cov-config=.coveragerc --cov=../covasim_schools --cov=../covasim_controller --cov=../school_tools test_*.py --workers auto --durations=0

echo 'Creating HTML report...'
coverage html

echo 'Running report...'
coverage report

echo 'Report location:'
echo "`pwd`/htmlcov/index.html"
