#!/bin/bash

echo 'Checking coverage...'
coverage run -m pytest test_* --durations=0

echo 'Creating HTML report...'
coverage html

echo 'Running report...'
coverage report

echo 'Report location:'
echo "`pwd`/htmlcov/index.html"